name = "LeanLean"
version = "0.1.0"
defaultTargets = ["leanlean"]

[[lean_lib]]
name = "LeanLean"

[[lean_lib]]
name = "Faithfulness.Accepted"

[[lean_exe]]
name = "leanlean"
root = "Main"

[[lean_exe]]
name = "leanleantest"
root = "Test"

[[lean_exe]]
name = "leanleanfaith"
root = "Faithfulness.Runner"

[[lean_exe]]
name = "leanleanimport"
root = "Faithfulness.ImportSmoke"
